[profile.default]
src = "src"
out = "out"
libs = ["/home/dracian/Projects/Inco/MillionairesDilemma_contracts/node_modules", "lib"]
evm_version = 'cancun'
solc = '0.8.28'
optimizer = true
via_ir = true
optimizer_runs = 1000
fs_permissions = [{ access = "read", path = "../node_modules"}]
  
[profile.gas_report]
via_ir = true
optimizer = true
optimizer_runs = 1000
