name: Millionaires Dilemma CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      
      - name: Install dependencies
        run: bun install
      
      - name: Run solhint
        run: cd contracts && bunx solhint "src/**/*.sol" --formatter stylish
        # Remove the "|| true" to make CI fail on linting errors

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.foundry
            contracts/cache
            contracts/out
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml', '**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-foundry-
      
      - name: Install dependencies
        run: bun install
      
      - name: Build contracts
        run: cd contracts && forge build --sizes
      
      - name: Run tests
        run: cd contracts && forge test -vvv
      
      - name: Generate gas report
        run: cd contracts && forge test --gas-report
        continue-on-error: true
      
      - name: Store gas report
        uses: actions/upload-artifact@v1
        with:
          name: gas-report
          path: contracts/gas-report.txt