name: Millionaires Dilemma CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      # Setup Bun instead of Node.js
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      # Copy dependencies into contracts directory
      - name: Prepare dependencies for Forge
        run: |
          # Create lib directory if it doesn't exist
          mkdir -p contracts/lib
          # Copy node_modules dependencies to contracts/lib
          cp -r node_modules/@inco contracts/lib/
          cp -r node_modules/@openzeppelin contracts/lib/
          cp -r node_modules/forge-std contracts/lib/
      
      - name: Build contracts
        run: cd contracts && forge build --sizes
      
      - name: Run tests
        run: cd contracts && forge test -vvv
        
      - name: Generate and display gas report
        run: cd contracts && forge test --gas-report | tee /tmp/gas-report.txt && cat /tmp/gas-report.txt
        continue-on-error: true